### ISSUE TITLE
Bcd fails when you use it in a dir that's not a subdir of /home

### ISSUE THREAD

**Issue by herulume** [pimonteiro/Small-interesting-scripts#1]
Since you're only searching inside /home it will fail when trying to locate dirs outside it. 
Change 
`my_array=( $(find /home -type d -name $DIR 2> /dev/null) )`
to
`my_array=( $(find / -type d -name $DIR 2> /dev/null) )`

**Comment by pimonteiro** [comment]
I could replace it (and i want to) but currently 'find / ......' gets stuck in some directory and i havent been able to find out why.

**Comment by herulume** [comment]
It works on my end.
![kaiokek](https://user-images.githubusercontent.com/9318723/35535429-745f5d90-053b-11e8-91b3-343d189174af.png)

Does take a bit longer, but since it's searching the entire filesystem it's normal.
